name: Web Automation Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run Test
      run: ./gradlew assembleDebug --info

    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: Cucumber Report
        path: reports
