name: Web Automation Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-test:
    runs-on: ubuntu-latest

    steps:
    # download repo
    - uses: actions/checkout@v3
    
    # setup java
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        
    # install chrome browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2
      with:
        chrome-version: 127
        install-chromedriver: true
      
    # setup graldew
    - name: Setup Gradle 8.5
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    # Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew test

    # Archive Test Result
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: Cucumber Report
        path: reports
