name: Web Automation Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # setup java
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        
    # install chrome browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome
      
    # setup graldew
    - name: Setup gradlew
      run: chmod +x gradlew 
      
    # Execute gradle 
    - name: Execute Test
      run: ./gradlew clean test

    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: Cucumber Report
        path: reports
